permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "the frugal wookie"
  description:
    A store dedicated to affordable nerd things!
  font_url: "https://fonts.googleapis.com/css?family=Alegreya+Sans:400,400i700|Source+Code+Pro:400,700"

  colors:
    background: "--color-neutral-beige"
    accent: "--color-primary-dark"
    patterns:
      brand.logos: "--color-primary-light"

  rationales:
    typefaces.primary: |
      Nanum Gothic Coding as the main display font to be used for titles and important information. It was selected becaus it is classic like the classic Star Wars films.
    typefaces.secondary: |
      Merriweather is chosen as a body text and will be used for large sections of text. It is serif based and can be easily read at smaller sizes.
    colors.primary: |
    The primary colors represent the classic movie tropes and the saving of money.
    colors.secomdary: |
    The secondary colors are only to be used to highlight certain sections or when the user has highlighted a button.
