description: |
  The banners are to be used to showcase the websites most important features.
  Banners can be combined with buttons, images, and the header.
patterns:
  banner:
    title: "Call To Action Banner"
    description: |
      The Call-To-Action banner is used only on the homepage.
    height: 400
    fields:
      - name: headermain
        type: string
        example: "Remember the past"
      - name: text
        type: string
        example: "The frorce is stong, with savings."
      - name: button_url
        type: string
        example: "/products/"
        required: false
      - name: button_text
        type: string
        example: "Shop Now"
        required: false
